name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq moreutils
          npm install

      - name: Process UCD XML to JSON
        run: |
          ./bin/ucd_download.sh
          ./bin/ucd_to_json.mts

      - name: Add gemoji data to JSON
        run: |
          ./bin/gemoji_download.sh
          ./bin/gemoji_add.mts

      - name: Set Status Info
        run: |
          ./bin/set_status.sh

      - name: Build
        run: |
          npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
